---
- name: "Installing MongoDB {{ mongodb_org_repo_version }} repository"
  yum_repository:
    name: "mongodb-org-{{ mongodb_org_repo_version }}"
    description: "MongoDB {{ mongodb_org_repo_version }} Repository"
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_org_repo_version }}/x86_64/"
    gpgcheck: yes
    enabled: "{{ mongodb_org_repo_enabled }}"
    gpgkey: "{{ mongodb_org_repo_gpg_key }}"

- name: "Importing MongoDB {{ mongodb_org_repo_version }} GPG key to the RPM database"
  rpm_key:
    key: "{{ mongodb_org_repo_gpg_key }}"
    state: present
